# Generated by Django 5.0.6 on 2024-09-22 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('club', models.CharField(choices=[('UIUDC', 'UIU Debate Club'), ('UIUCC', 'UIU Cultural Club'), ('UIUTFC', 'UIU Theater & Film Club'), ('UIUBC', 'UIU Business Club'), ('UIUCCL', 'UIU Computer Club'), ('UIUEEC', 'UIU Electrical & Electronic Club'), ('UIUPC', 'UIU Photography Club'), ('UIUSSC', 'UIU Social Services Club'), ('UIUSC', 'UIU Sports Club'), ('UIUMC', 'UIU MBA Club'), ('UIUAF', 'UIU APP FORUM')], max_length=100)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
