# Generated by Django 5.0.6 on 2024-09-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0003_job_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='deadline',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry_level', 'Entry-Level'), ('mid_level', 'Mid-Level'), ('senior_level', 'Senior-Level'), ('all_levels', 'All Experience Levels')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, choices=[('it', 'Information Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('others', 'Others (Specify)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='industry_specification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_environment',
            field=models.CharField(blank=True, choices=[('in_office', 'In-Office'), ('hybrid', 'Hybrid'), ('remote', 'Fully Remote')], max_length=20, null=True),
        ),
    ]
