# Generated by Django 5.0.6 on 2024-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0005_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
