# Generated by Django 5.0.6 on 2024-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('item_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('time_date', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
