# Generated by Django 5.0.6 on 2024-09-09 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='found_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='post_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
