# Generated by Django 5.0.6 on 2024-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0002_item_found_by_item_post_status_item_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='found_by',
        ),
        migrations.AddField(
            model_name='item',
            name='found_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
