# Generated by Django 5.0.6 on 2024-08-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('code', models.IntegerField(max_length=11)),
                ('status', models.IntegerField(max_length=1)),
            ],
            options={
                'db_table': 'verification_codes',
            },
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
