# Generated by Django 5.0.6 on 2024-08-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverification',
            table=None,
        ),
    ]
