# Generated by Django 5.0.6 on 2024-08-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_emailverification_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
