# Generated by Django 5.0.6 on 2024-08-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_emailverification_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverification',
            table='verification_codes',
        ),
    ]
