# Generated by Django 5.0.6 on 2024-08-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_alter_emailverification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
