# Generated by Django 5.0.6 on 2024-09-08 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_alter_temporaryuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
