# Generated by Django 5.0.6 on 2024-09-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thesismemberprofile',
            table='thesis_member_profiles',
        ),
    ]
