# Generated by Django 5.0.6 on 2024-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_finder', '0002_alter_thesismemberprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesismemberprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
