# Generated by Django 5.0.6 on 2024-09-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_finder', '0003_thesismemberprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesismemberprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
