# Generated by Django 5.0.6 on 2024-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('DS', 'Data Science Engineering'), ('EE', 'Electrical & Electronics Engineering'), ('CE', 'Civil Engineering'), ('PH', 'Pharmacy'), ('BT', 'Biotechnology & Genetic Engineering'), ('EN', 'English'), ('BA', 'Business Administration'), ('MBA', 'MBA'), ('MJ', 'Media & Journalism'), ('ECO', 'Economics')], max_length=100)),
                ('trimester_semester', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('slides', 'Slides'), ('assignment', 'Assignment'), ('ct_question', 'CT Question'), ('mid_question', 'Mid Question'), ('final_question', 'Final Question'), ('class_notes', 'Class Notes')], max_length=20)),
                ('material_description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('admin_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
                'ordering': ['upload_date'],
            },
        ),
    ]
