# Generated by Django 5.0.6 on 2024-09-19 03:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials_and_feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={},
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='trimester_semester',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='degree',
            field=models.CharField(default='Unknown Degree', max_length=255),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course_materials_and_feedback.coursematerial')),
            ],
        ),
    ]
