# Generated by Django 5.0.6 on 2024-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials_and_feedback', '0002_alter_coursematerial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='trimester',
            field=models.CharField(default='Unknown Trimester', max_length=255),
        ),
    ]
