# Generated by Django 5.0.6 on 2024-09-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials_and_feedback', '0003_coursematerial_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='course_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
